# -*- coding: utf-8 -*-
"""CV-LAB-08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ue-LSda2yLvRmVkLcAYUqN_CoPZNPMP2

First, let's download a sample image to work with.
"""

import cv2
from google.colab.patches import cv2_imshow

img = cv2.imread('Picture4.jpg')

if img is None:
    print("Error: Could not load image 'image1.jpg'. Please ensure the file exists.")
else:
    height, width = img.shape[:2]
    scale_factor = 2.0
    new_width_large = int(width * scale_factor)
    new_height_large = int(height * scale_factor)

    img_bigger = cv2.resize(
        img,
        (new_width_large, new_height_large),
        interpolation=cv2.INTER_CUBIC
    )

    new_width_small = int(width * 0.5)
    new_height_small = int(height * 0.5)

    img_smaller = cv2.resize(
        img,
        (new_width_small, new_height_small),
        interpolation=cv2.INTER_AREA
    )

    # Display images
    print("Original Image")
    cv2_imshow(img)

    print("Bigger Image")
    cv2_imshow(img_bigger)

    print("Smaller Image")
    cv2_imshow(img_smaller)

    cv2.imwrite('bigger_image1.jpg', img_bigger)
    cv2.imwrite('smaller_image1.jpg', img_smaller)
    print("Images processed and saved: 'bigger_image1.jpg' and 'smaller_image.jpg'")