# -*- coding: utf-8 -*-
"""CV-LAB-09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zcPSDXna26lA0IikyU8dPuE7q407yDvc
"""

import cv2
from google.colab.patches import cv2_imshow

image = cv2.imread('Picture2.jpg')

if image is None:
    print("Error: Could not load image. Check the file path.")
else:
    clockwise_90 = cv2.rotate(image, cv2.ROTATE_90_CLOCKWISE)

    counter_clockwise_90 = cv2.rotate(image, cv2.ROTATE_90_COUNTERCLOCKWISE)

    cv2.imwrite('rotated_clockwise.png', clockwise_90)
    cv2.imwrite('rotated_counter_clockwise.png', counter_clockwise_90)

    print("Original Image:")
    cv2_imshow(image)
    print("Clockwise (90°):")
    cv2_imshow(clockwise_90)
    print("Counter-Clockwise (90°):")
    cv2_imshow(counter_clockwise_90)