# -*- coding: utf-8 -*-
"""CV-LAB-12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rkSPhbF8dNjmzwzjrITaJPcaoq9BdScC
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

img = cv2.cvtColor(cv2.imread(list(files.upload().keys())[0]), cv2.COLOR_BGR2RGB)
h, w = img.shape[:2]

src = np.float32([[100,50],[w-100,20],[50,h-50],[w-50,h-100]])
dst = np.float32([[0,0],[300,0],[0,300],[300,300]])

M = cv2.getPerspectiveTransform(src, dst)
out = cv2.warpPerspective(img, M, (300,300))

plt.figure(figsize=(8,4))
plt.subplot(121)
plt.imshow(img)
plt.title("Original")
plt.axis("off")

plt.subplot(122)
plt.imshow(out)
plt.title("Perspective Transform")
plt.axis("off")

plt.show()